apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiment-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: experiment-deployment
  template:
    metadata:
      labels:
        app: experiment-deployment
    spec:
      containers:
      - name: experiment-deployment
        image: mcr.microsoft.com/azuredocs/aci-helloworld
        ports:
        - containerPort: 80

